language: node_js
node_js:
  - '0.12'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages

after_script:
  - 'gulp karma' 

notifications:
  slack:
    rooms:
      - fachgruppeuiux:UouB0QTvbtA3Wk3nXf5aLmjA#creativenetwork
  