language: node_js
node_js:
  - '0.12'

script: cd Source && npm install && bower install && npm test

notifications:
  slack:
    rooms:
      - fachgruppeuiux:UouB0QTvbtA3Wk3nXf5aLmjA#creativenetwork
  