language: node_js
node_js:
  - '0.12'
  
 before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages